#!/bin/sh
#
# Simple script that returns Arch's kernel version.
#
# Author: Dimitris Gerasimou <https://github.com/dimgerasimou>


kern="$(uname -r | sed -re 's/(^[0-9]*\.[0-9]*\.[0-9]*)(.*)/\1/')"

echo -e "🐧 $kern"
