[plugins]
"rocks.nvim"                  = "2.44.0"
"rocks-config.nvim"           = "3.1.0"
"rocks-git.nvim"              = "2.5.3"
"rocks-treesitter.nvim"       = "1.3.0"
"rocks-lazy.nvim"             = "1.2.0"
friendly-snippets             = "scm"
catpuccin                     = "1.9.0"
nvim-lspconfig                = "1.8.0"
"comment.nvim"                = "0.8.0"
"persisted.nvim"              = "2.1.0"
"gitsigns.nvim"               = "1.0.2"
alpha-nvim                    = "scm"
"telescope.nvim"              = "scm"
"aerial.nvim"                 = "2.5.0"
"trouble.nvim"                = "3.7.1"
"indent-blankline.nvim"       = "3.9.0"
"rainbow-delimiters.nvim"     = "0.9.1"
nvim-ts-context-commentstring = "scm"
tree-sitter-lua               = "0.0.34"
tree-sitter-latex             = "0.0.33"
"neo-tree.nvim"               = "3.31.1"
"lualine.nvim"                = "scm"
nvim-cokeline                 = "scm"
"lazydev.nvim"                = "1.9.0"
"which-key.nvim"              = "3.17.0"
"clangd_extensions.nvim"      = "scm"
luasnip = "2.3.0"
nvim-treesitter-legacy-api = "0.9.2"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.1.1"
build = "cargo build --release"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "1f08ed60cafc8f6168b72b80be2b2ea149813e55"
build = "make"

[plugins."multiple-cursors.nvim"]
git = "brenton-leighton/multiple-cursors.nvim"
rev = "v0.15"

[plugins.vimtex]
git = "lervag/vimtex"

[bundles.lsp]
items = [
	'clangd_extensions.nvim',
	'nvim-lspconfig'
]

[config]
plugins_dir = "plugins/"
