[plugins]
"rocks.nvim" = "2.31.3"
"rocks-config.nvim" = "2.0.0"
"rocks-git.nvim" = "1.5.1"
neorg = "8.7.1"
catpuccin = "1.7.0"
"neo-tree.nvim" = "3.26"
"rainbow-delimiters.nvim" = "0.4.0"
"comment.nvim" = "0.8.0"
nvim-ts-context-commentstring = "scm"
"lualine.nvim" = "scm"
"toggleterm.nvim" = "2.11.0"
"indent-blankline.nvim" = "3.6.2"
nvim-treesitter= "0.9.2"
"better-escape.nvim" = "1.0.0"
"smart-splits.nvim" = "1.5.0"
bufresize = { git = "kwkarlwang/bufresize.nvim" }
"which-key.nvim" = "2.1.0"
nvim-cokeline = "0.4.0"
"persisted.nvim" = "scm"
"telescope.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make"}
alpha-nvim = "scm"
vimtex = { git = "lervag/vimtex" }
nvim-window-picker = { git = "s1n7ax/nvim-window-picker" }

# LSP - snip - cmp configuration
"neodev.nvim" = "3.0.0"
nvim-lspconfig = "0.1.8"
nvim-cmp = "0.0.1"
luasnip = "2.3.0"
"clangd_extensions.nvim" = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-git = "scm"
cmp-cmdline = "scm"
cmp-emoji = { git = "hrsh7th/cmp-emoji" }
cmp-nvim-lua = { git = "hrsh7th/cmp-nvim-lua" }
cmp-plugins = { git = "KadoBOT/cmp-plugins" }
cmp-calc = { git = "hrsh7th/cmp-calc" }
cmp-nvim-lsp = "scm"
cmp_luasnip = "scm"
nvim-cmp-lua-latex-symbols = { git = "amarakon/nvim-cmp-lua-latex-symbols" }
"lspkind.nvim" = "scm"
"image.nvim" = "1.3.0"


"trouble.nvim" = "3.4.2"
"aerial.nvim" = "1.7.0"
"nabla.nvim" = "scm"
"headlines.nvim" = "4.0.1"
"mini.nvim" = "0.9.0"
"multiple-cursors.nvim" = { git = "brenton-leighton/multiple-cursors.nvim" }
"xkbswitch.nvim" = { git = "dimgerasimou/xkbswitch.nvim" }

[bundles.lsp]
items = [
	"neodev.nvim",
	"nvim-lspconfig",
	"nvim-cmp",
	"luasnip",
	"cmp-git",
	"cmp-plugins",
	"clangd_extensions.nvim",
	"lspkind.nvim",
]

[config]
plugins_dir = "plugins/"
